#pragma once

#include <cstdint>

// Generated by benchmarks/generate_gemm_swiglu_hybrid_policy.py
// Acceptance gate: custom V7 speedup >= 1.050x in all 2 runs.
namespace cuda_operator_lab::generated {

constexpr std::uint64_t kGemmSwiGluCustomMaxM = 128ULL;
constexpr std::uint64_t kGemmSwiGluCustomMaxK = 128ULL;
constexpr std::uint64_t kGemmSwiGluCustomMaxN = 2048ULL;

inline bool gemm_swiglu_use_custom_v7(
    std::uint64_t m,
    std::uint64_t k,
    std::uint64_t n) {
  return m <= kGemmSwiGluCustomMaxM &&
         k <= kGemmSwiGluCustomMaxK &&
         n <= kGemmSwiGluCustomMaxN &&
         (m % 16ULL) == 0ULL &&
         (k % 16ULL) == 0ULL &&
         (n % 64ULL) == 0ULL;
}

}  // namespace cuda_operator_lab::generated
